title: "Ignasia Consulting"
description: "Expert audit, consulting, and business process optimization services specializing in governance, risk, compliance, and cybersecurity."
email: "info@ignasia.consulting"
phone: "+91 123 456 7890"
address: "Mumbai, India"
linkedin: "https://www.linkedin.com/company/ignasia/"
website: "https://ignasia.netlify.app"